name: Format Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint_and_format_check:
    runs-on: ubuntu-22.04
    name: Run Linting and Format Check
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.1'

      - name: Install dependencies
        working-directory: app
        run: npm install

      - name: Check code formatting with Prettier
        working-directory: app
        run: npm run format:check || true  # Ignoriere Fehler, falls nötig
